### ISSUE TITLE
Not Found:from content_word_utils import retrieve

### ISSUE THREAD

**Issue by Funny-Panda** [terne/spurious_correlations_in_argmin#1]
Hello, I can't find module or package which named content_word_utils or retrieve. Does it need to be installed or is it stored in the project as an accessory but not provided?

**Comment by Funny-Panda** [comment]
> Hello, I can't find module or package which named content_word_utils or retrieve. Does it need to be installed or is it stored in the project as an accessory but not provided?

In the file named unl_data_proc.py, at line 5.

**Comment by terne** [comment]
Thank you for your comment, it was unavailable because of my forgetfulness. The scripts are in the repo now, give it a go! :)

**Comment by Funny-Panda** [comment]
Sincerely thank you for your reply！
